import { Fustat, Bricolage_Grotesque, Rethink_Sans } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/Footer/Footer'

const fustatFont = Fustat({
  variable: '--font-fustat',
  subsets: ['latin'],
})
const bricolageGrotesque = Bricolage_Grotesque({
  variable: '--font-bricolage-grotesque',
  subsets: ['latin'],
})
const rethinkSans = Rethink_Sans({
  variable: '--font-rethink-sans',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${fustatFont.variable} antialiased bg-[#013A33] overflow-x-hidden `}
      >
        <Navbar />
        <div
          className={`bg-[url('/Frame.png')] bg-cover bg-no-repeat h-full mx-auto max-w-[1440px]`}
        >
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
